### ISSUE TITLE
Trying to mention somebody, the "@" disappears

### ISSUE THREAD

**Issue by NPrice99** [Eickhel/PowerApps-samples#2]
Hi 

When I try and mention somebody in a tweet, using PowerTwitter,  eg@Nigel_Price .  The "@" is missed off from the tweeted tweet.

Regards

Nigel

**Comment by Eickhel** [comment]
Hey,

It's a know issue with the Twitter connector. I think it's best to use a custom connector. The downside is that you will run into license issues.
