### ISSUE TITLE
Import PowerFont zip file fails

### ISSUE THREAD

**Issue by troystaylor** [Eickhel/PowerApps-samples#4]
I've downloaded the PowerFont.msapp you've provided to view the code required to display a Base64 font, but I'm unable to import the zip file I created into PowerApps

![msedge_gPSJX6AiHI](https://user-images.githubusercontent.com/44444967/64721736-1773df80-d49b-11e9-8332-88f585c727e4.png)

**Comment by Eickhel** [comment]
Hey,

PowerFont has not been released as a Zip file but as a .msapp file. You can open that file from the PowerApps portal.
